config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "submissions#index"
  resources :submissions do
    member do
      put "like", to: "submissions#like"
      put "unlike", to: "submissions#unlike"
    end
    resources :comments
  end
  resources :comments, except: [:new, :show] do
    member do
      put "like", to: "comments#like"
      put "unlike", to: "comments#unlike"
    end
    resources :comments
  end
  get '/newest' => 'pages#newest', as: :newest
  get ':id/not_found' => 'pages#missing', as: :missing
  get ':id' => 'pages#profile'
  get ':id/submissions' => 'pages#user_submissions', as: :user_submissions
  get ':id/comments' => 'pages#user_comments', as: :user_comments
  get ':id/favorites' => 'pages#user_favorites', as: :user_favorites
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  acts_as_votable

  scope :newest_first, lambda {order("created_at DESC")}

  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable

  validates_presence_of :body
end

app/models/submission.rb
class Submission < ApplicationRecord
  acts_as_votable

  scope :newest_first, lambda {order("created_at DESC")}

  belongs_to :user
  has_many :comments, as: :commentable

  validates_presence_of :title
  validates_presence_of :url
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_voter

  validates :username, uniqueness: true

  def email_required?
    false
  end

  def email_changed?
    false
  end

  has_many :submissions, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :password, :password_confirmation, :remember_me])
      devise_parameter_sanitizer.permit(:sign_in, keys: [:username, :password, :password_confirmation, :remember_me])
      devise_parameter_sanitizer.permit(:account_update, keys: [:username, :about, :password, :password_confirmation, :remember_me])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy, :like, :unlike]
  before_action :set_commentable, only: [:create]
  before_action :authenticate_user!

  def index
    @comments = Comment.all.newest_first
  end

  def edit
  end

  def create
    @comment = @commentable.comments.new(comment_params)
    @comment.parent_id = @comment.commentable_type == 'Submission' ? @commentable.id : @commentable.parent_id
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to :back, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { redirect_to :back }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to :back, notice: 'Comment was successfully updated.' }
        format.json { render json: @comment, status: :ok, location: @comment }
      else
        format.html { redirect_to :back }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    @comment.liked_by current_user
    redirect_to :back
  end

  def unlike
    @comment.unliked_by current_user
    redirect_to :back
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_commentable
      @commentable = Comment.find(params[:comment_id]) if params[:comment_id]
      @commentable = Submission.find(params[:submission_id]) if params[:submission_id]
    end

    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :set_user, except: [:newest, :missing]

	def profile
		@karma = (@user.submissions.map{|s| s.get_upvotes.count}.sum) + (@user.comments.map{|c| c.get_upvotes.count}.sum)
	end

  def newest
    @submissions = Submission.all.newest_first
  end

	def user_submissions
		@user_submissions = @user.submissions.newest_first
	end

	def user_comments
		@user_comments = @user.comments.newest_first
	end

	def user_favorites
		@likes = @user.find_voted_items
		@liked_submissions = @likes.select { |i| i.class.name == "Submission" }
		@liked_comments = @likes.select { |i| i.class.name == "Comment" }
	end

	def missing
	end

	private
    def set_user
			if (User.find_by_username(params[:id]))
				@username = params[:id]
				@user = User.find_by_username(@username)
			else
				redirect_to missing_path, :notice => "User not found"
			end
    end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: [:show, :edit, :update, :destroy, :like, :unlike]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @submissions = Submission.order(cached_votes_total: :desc)
  end

  def show
  end

  def new
    @submission = current_user.submissions.new
  end

  def edit
  end

  def create
    @submission = Submission.new(submission_params)

    respond_to do |format|
      if @submission.save
        format.html { redirect_to @submission, notice: 'Submission was successfully created.' }
        format.json { render :show, status: :created, location: @submission }
      else
        format.html { render :new }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url, notice: 'Submission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    @submission.liked_by current_user
    redirect_to :back
  end

  def unlike
    @submission.unliked_by current_user
    redirect_to :back
  end

  private
    def set_submission
      @submission = Submission.find(params[:id])
    end

    def submission_params
      params.require(:submission).permit(:title, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/comments/_comment.html.erb
<li>
  <div class="comments-wrapper clearfix">
    <div class="null-left">
      <% if user_signed_in? && (current_user.voted_for? comment) %>
        <%= awesome_link('fa fa-caret-up fa-2x used', unlike_comment_path(comment), method: :put) %>
      <% else %>
        <%= awesome_link('fa fa-caret-up fa-2x', like_comment_path(comment), method: :put) %>
      <% end %>
      <p><small> <%= link_to comment.user.username, "/#{comment.user.username}" %> <strong><%= time_ago_in_words(comment.created_at) %></strong> ago </small></p>
      <p class="lead">
        <% if user_signed_in? && comment.user == current_user %>
          <%= best_in_place comment, :body, :as => :textarea, :ok_button => 'Save', :cancel_button => 'Cancel' %>
        <% else %>
          <%= comment.body %>
        <% end %>
      </p>
      <p><%= comment.get_upvotes.size %> points</p>
    </div>
  </div>

  <% if comment.user == current_user %>
    <%= link_to 'delete', comment, method: :delete, data: { confirm: 'are you sure?'} %>
  <% end %>

  <%= form_for [comment, Comment.new] do |f| %>
    <%= f.text_area :body, placeholder: "Add a reply" %><br/>
    <%= f.submit "add reply"  %>
  <% end %>

  <ul>
    <%= render(partial: 'comments/comment', collection: comment.comments) %>
  </ul>
</li>

app/views/comments/index.html.erb
<%= provide(:page_title, "New Comments") %>

<table>
  <tbody>
    <% @comments.each do |comment| %>
      <tr class="post">
        <td>
          <div class="comments-wrapper clearfix">
            <div class="null-left">
              <% if user_signed_in? && (current_user.voted_for? comment) %>
                <%= awesome_link('fa fa-caret-up fa-2x used', unlike_comment_path(comment), method: :put) %>
              <% else %>
                <%= awesome_link('fa fa-caret-up fa-2x', like_comment_path(comment), method: :put) %>
              <% end %>
              <p><small> <%= link_to comment.user.username, "/#{comment.user.username}" %> <strong><%= time_ago_in_words(comment.created_at) %></strong> ago | <%= link_to "on: {Submission.find(comment.submission_id)}", Submission.find(comment.parent_id) %></small></p>
              <p class="lead">
                <%= comment.body %>
              </p>
              <p><%= comment.get_upvotes.size %> points</p>
            </div>
          </div>

          <% if comment.user == current_user %>
            <%= link_to 'delete', comment, method: :delete, data: { confirm: 'are you sure?'} %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_navbar.html.erb
<% if !(yield(:page_title) == ('Sign Up') || yield(:page_title) == ('Log In')) %>
  <header class="navbar navbar-default" role="navigation">
    <div class="navbar-brand">
      <%= link_to "Hacker News", root_path %>
    </div>
    <nav class="collapse navbar-collapse navbar-ex-1-collapse">
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "new", newest_path %></li>
        <li><%= link_to "comments", comments_path %></li>
        <li><%= link_to "submit", new_submission_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "account", edit_user_registration_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "logout", destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to "login", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </header>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %></title>
    <%= favicon_link_tag asset_path('favicon.png'), :rel => 'icon', :type =>  'image/png' %>
    <%= csrf_meta_tags %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="main" class="container">
      <%= render 'layouts/navbar' %>

      <% if flash.any? %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      <% end %>

      <div id="container" class="center-block">
        <%= yield %>
      </div>

    </div>
  </body>
</html>

app/views/pages/missing.html.erb
<% provide(:page_title, 'User Not Found') %>

app/views/pages/newest.html.erb
<%= provide(:page_title, 'New Links | Hacker News') %>

<table>
  <tbody>
    <% @submissions.each do |submission| %>
      <tr class="post">
        <td>
          <% if user_signed_in? && (current_user.voted_for? submission) %>
            <%= awesome_link('fa fa-caret-up fa-2x used', unlike_submission_path(submission), method: :put) %>
          <% else %>
            <%= awesome_link('fa fa-caret-up fa-2x', like_submission_path(submission), method: :put) %>
          <% end %>
          <%= link_to submission.title, submission.url, class: "title" %>
          <%= link_to "(#{submission.url})", submission.url, target: "_blank" %>
        </td>
        <tr class="post">
          <td> <p><%= submission.get_upvotes.size %> points by <%= submission.user.username %> <%= time_ago_in_words(submission.created_at) %> ago | <%= link_to "#{submission.comments.count} comments", submission %> </p></td>
        </tr>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pages/profile.html.erb
<%= provide(:page_title, "Profile: #{@user.username}") %>

<table>
  <tbody>
    <tr>
      <td>user: </td>
      <td><%= @user.username %></td>
    </tr>
    <tr>
      <td>created: </td>
      <td><%= @user.created_at %></td>
    </tr>
    <tr>
      <td>karma: </td>
      <td><%= @karma %></td>
    </tr>
    <tr>
      <td>about: </td>
      <td><%= @user.about %></td>
    </tr>
    <tr>
      <td></td>
      <td><%= link_to 'Submissions', user_submissions_path %></td>
    </tr>
    <tr>
      <td></td>
      <td><%= link_to 'Comments', user_comments_path %></td>
    </tr>
    <tr>
      <td></td>
      <td><%= link_to 'Favorites', user_favorites_path %></td>
    </tr>
  </tbody>
</table>

app/views/pages/user_comments.html.erb
<%= provide(:page_title, "#{@user.username}'s comments") %>

<table>
  <tbody>
    <% @user_comments.each do |comment| %>
      <tr class="post">
        <td>
          <div class="comments-wrapper clearfix">
            <div class="null-left">
              <% if user_signed_in? && (current_user.voted_for? comment) %>
                <%= awesome_link('fa fa-caret-up fa-2x used', unlike_comment_path(comment), method: :put) %>
              <% else %>
                <%= awesome_link('fa fa-caret-up fa-2x', like_comment_path(comment), method: :put) %>
              <% end %>
              <p><small> <%= link_to @user.username, "/#{@user.username}" %> <strong><%= time_ago_in_words(comment.created_at) %></strong> ago | <%= link_to "on: {Submission.find(comment.submission_id)}", Submission.find(comment.parent_id) %></small></p>
              <p class="lead">
                <%= comment.body %>
              </p>
              <p><%= comment.get_upvotes.size %> points</p>
            </div>
          </div>

          <% if comment.user == current_user %>
            <%= link_to 'delete', comment, method: :delete, data: { confirm: 'are you sure?'} %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pages/user_favorites.html.erb
<%= provide(:page_title, "#{@user.username}'s favorites") %>

<nav id="profile-nav">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myActivity">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="collapse navbar-collapse" id="myActivity">
        <ul class="nav navbar-nav">
          <li data-index="submissions"><a href="#submissions">Submissions</a></li>
          <li data-index="comments"><a href="#comments">Comments</a></li>
        </ul>
      </div>
    </div>
  </div>
</nav>
<section class="content" data-index="submissions">
  <table>
    <tbody>
      <% if @liked_submissions.count > 0 %>
        <% @liked_submissions.each do |submission| %>
          <tr class="post">
            <td>
              <% if user_signed_in? && (current_user.voted_for? submission) %>
                <%= awesome_link('fa fa-caret-up fa-2x used', unlike_submission_path(submission), method: :put) %>
              <% else %>
                <%= awesome_link('fa fa-caret-up fa-2x', like_submission_path(submission), method: :put) %>
              <% end %>
              <%= link_to submission.title, submission.url, class: "title" %>
              <%= link_to "(#{submission.url})", submission.url, target: "_blank" %>
            </td>
            <tr class="post">
              <td> <p><%= submission.get_upvotes.size %> points by <%= submission.user.username %> <%= time_ago_in_words(submission.created_at) %> ago | <%= link_to "#{submission.comments.count} comments", submission %> </p></td>
            </tr>
          </tr>
        <% end %>
      <% else %>
        <p><%= @user.username %> hasn't added any favorite submissions yet</p>
      <% end %>
    </tbody>
  </table>
</section>
<section class="content" data-index="comments">
  <table>
    <tbody>
      <% if @liked_comments.count > 0 %>
        <% @liked_comments.each do |comment| %>
          <tr class="post">
            <td>
              <div class="comments-wrapper clearfix">
                <div class="null-left">
                  <% if user_signed_in? && (current_user.voted_for? comment) %>
                    <%= awesome_link('fa fa-caret-up fa-2x used', unlike_comment_path(comment), method: :put) %>
                  <% else %>
                    <%= awesome_link('fa fa-caret-up fa-2x', like_comment_path(comment), method: :put) %>
                  <% end %>
                  <p><small> <%= comment.user.username %> <strong><%= time_ago_in_words(comment.created_at) %></strong> ago | <%= link_to "on: {Submission.find(comment.submission_id)}", Submission.find(comment.parent_id) %></small></p>
                  <p class="lead">
                    <%= comment.body %>
                  </p>
                  <p><%= comment.get_upvotes.size %> points</p>
                </div>
              </div>

              <% if comment.user == current_user %>
                <%= link_to 'delete', comment, method: :delete, data: { confirm: 'are you sure?'} %>
              <% end %>
            </td>
          </tr>
        <% end %>
      <% else %>
        <p><%= @user.username %> hasn't added any favorite comments yet</p>
      <% end %>
    </tbody>
  </table>
</section>

app/views/pages/user_submissions.html.erb
<%= provide(:page_title, "#{@user.username}'s favorite submissions") %>

<table>
  <tbody>
    <% @user_submissions.each do |submission| %>
      <tr class="post">
        <td>
          <% if user_signed_in? && (current_user.voted_for? submission) %>
            <%= awesome_link('fa fa-caret-up fa-2x used', unlike_submission_path(submission), method: :put) %>
          <% else %>
            <%= awesome_link('fa fa-caret-up fa-2x', like_submission_path(submission), method: :put) %>
          <% end %>
          <%= link_to submission.title, submission.url, class: "title" %>
          <%= link_to "(#{submission.url})", submission.url, target: "_blank" %>
        </td>
        <tr class="post">
          <td> <p><%= submission.get_upvotes.size %> points by <%= submission.user.username %> <%= time_ago_in_words(submission.created_at) %> ago | <%= link_to "#{submission.comments.count} comments", submission %> </p></td>
        </tr>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/submissions/_form.html.erb
<%= form_for(submission) do |f| %>
  <% if submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
      <% submission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_area :title %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_area :url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/submissions/index.html.erb
<%= provide(:page_title, 'Hacker News') %>

<table>
  <tbody>
    <% @submissions.each do |submission| %>
      <tr class="post">
        <td>
          <% if user_signed_in? && (current_user.voted_for? submission) %>
            <%= awesome_link('fa fa-caret-up fa-2x used', unlike_submission_path(submission), method: :put) %>
          <% else %>
            <%= awesome_link('fa fa-caret-up fa-2x', like_submission_path(submission), method: :put) %>
          <% end %>
          <%= link_to submission.title, submission.url, class: "title" %>
          <%= link_to "(#{submission.url})", submission.url, target: "_blank" %>
        </td>
        <tr class="post">
          <td> <p><%= submission.get_upvotes.size %> points by <%= link_to submission.user.username, "#{submission.user.username}" %> <%= time_ago_in_words(submission.created_at) %> ago | <%= link_to "#{submission.comments.count} comments", submission %> </p></td>
        </tr>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/submissions/new.html.erb
<% provide(:page_title, 'New Submission') %>

<h1>New Submission</h1>

<%= render 'form', submission: @submission %>

<%= link_to 'Back', submissions_path %>

app/views/submissions/show.html.erb
<% provide(:page_title, @submission.title) %>

<div class="page-header">
  <h4>
    <% if user_signed_in? && (current_user.voted_for? @submission) %>
      <%= awesome_link('fa fa-caret-up fa-2x used', unlike_submission_path(@submission), method: :put) %>
    <% else %>
      <%= awesome_link('fa fa-caret-up fa-2x', like_submission_path(@submission), method: :put) %>
    <% end %>
    <%= best_in_place @submission, :title, :as => :textarea, :ok_button => 'Save', :cancel_button => 'Cancel' %>
    <a href="<%= @submission.url %>"><%= best_in_place @submission, :url %></a>
  </h4>
  <p><%= @submission.get_upvotes.size %> points by <%= @submission.user.username %> <%= time_ago_in_words(@submission.created_at) %> ago | <%= link_to "#{@submission.comments.count} comments", @submission %> </p>
  <br>
  <%= form_for [@submission, Comment.new] do |f| %>
    <%= f.text_area :body, placeholder: "Add a comment" %>
    <br>
    <%= f.submit "add comment" %>
  <% end %>
  <ul id="comments">
    <%= render(partial: 'comments/comment', collection: @submission.comments) %>
  </ul>
</div>